spring.application.name=textrag

server.port=8080

spring.ai.vertex.ai.gemini.project-id=mcp-org
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-pro

### Local DB
spring.datasource.url=jdbc:postgresql://localhost:5432/work
spring.datasource.username=shaama
spring.datasource.password=xyz
spring.datasource.driver-class-name=org.postgresql.Driver

### Embeddings
spring.ai.vertex.ai.embedding.project-id=mcp-org
spring.ai.vertex.ai.embedding.location=us-central1
spring.ai.vertex.ai.embedding.text.options.model=text-embedding-005

### PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.remove-existing-vector-store-table=true
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.table-name=velocity_motors_data
spring.ai.vectorstore.pgvector.schema-validation=false
